version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - snyk/scan
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t fbenard/mao-service-registry:latest .
      - snyk/scan:
          docker-image-name: fbenard/mao-service-registry:latest
          target-file: "Dockerfile"

workflows:
  my-workflow:
    jobs:
      - my-job
