version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build test image
          command: docker build -t fbenard/mao-service-registry --target test .
      - run:
          name: Run tests
          command: docker run --env MAO_CORE_SERVER_HOST=${MAO_CORE_SERVER_HOST} --env MAO_CORE_SERVER_PORT=${MAO_CORE_SERVER_PORT} -it --rm fbenard/mao-service-registry
      - run:
          name: Build production image
          command: docker build -t fbenard/mao-service-registry --target production .
      - snyk/scan:
          docker-image-name: fbenard/mao-service-registry
          target-file: "Dockerfile"
      - run:
          name: Push image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag fbenard/mao-service-registry fbenard/mao-service-registry:${CIRCLE_SHA1}

workflows:
  my-workflow:
    jobs:
      - my-job
